[build]
  command = "hugo --gc --minify"
  publish = "public"

[build.environment]
  HUGO_VERSION = "0.84.0"

[[redirects]]
  from = "/download"
  to = "https://chrome.google.com/webstore/detail/mgg-t%C3%ACm-m%C3%A3-gi%E1%BA%A3m-gi%C3%A1-khuy%E1%BA%BF/ifopcmdhkclfibobkihammcldjbmidnm"
  status = 301
  force = true
